default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_development
  url: <%= ENV.fetch("DATABASE_URL", nil) %>

test:
  <<: *default
  database: app_test

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>
